# Generated by Django 5.2.4 on 2025-08-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_delete_message", "Удаление сообщения"),
                    ("can_update_message", "Обновление сообщения"),
                    ("can_create_message", "Добавление сообщения"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
