# Generated by Django 5.2.4 on 2025-08-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
