# Generated by Django 5.2.4 on 2025-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_message_delete_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="recipients",
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="mailing.recipientmailing", verbose_name="Получатели сообщения"
            ),
        ),
    ]
