# Generated by Django 5.2.4 on 2025-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_mailing_recipients_mailing_recipients"),
        ("recipients", "0002_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="recipients.recipient", verbose_name="Получатели сообщения"
            ),
        ),
        migrations.DeleteModel(
            name="RecipientMailing",
        ),
    ]
