# Generated by Django 5.2.4 on 2025-08-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_recipients_delete_recipientmailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_delete_mailing", "Удаление рассылки"),
                    ("can_update_mailing", "Обновление рассылки"),
                    ("can_create_mailing", "Добавление рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
