# Generated by Django 5.2.4 on 2025-08-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_all_view_mailing", "Просмотр всех рассылок"),
                    ("can_delete_mailing", "Удаление рассылки"),
                    ("can_update_mailing", "Обновление рассылки"),
                    ("can_create_mailing", "Добавление рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
