# Generated by Django 5.2.4 on 2025-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="status_mail",
            field=models.TextField(default="", verbose_name="Текстовый статус"),
            preserve_default=False,
        ),
    ]
