# Generated by Django 5.2.4 on 2025-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_mailing_status_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status_ending",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
