# Generated by Django 5.2.4 on 2025-07-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                ("comments", models.TextField(verbose_name="Комментарий")),
            ],
        ),
    ]
