# Generated by Django 5.2.4 on 2025-08-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
    ]
